version: "1.0"

services:
  botpress:
    image: botpress/server:latest
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
    env:
      - BP_PRODUCTION=true
      - DATABASE_URL=postgres://bp_user:PG_PASSWORD@postgres:5432/botpress_db
      - REDIS_URL=redis://redis:6379?password=redisPassword
      - BP_MODULE_NLU_DUCKLINGURL=http://duckling:8000
      - BP_MODULE_NLU_LANGUAGESOURCES=[{"endpoint":"http://lang:3100"}]
      - CLUSTER_ENABLED=false
      - BPFS_STORAGE=database
      - BP_MAX_SERVER_REBOOT=999
  duckling:
    image: rasa/duckling:latest
    expose:
      - port: 8000
        as: 8000
        to:
          - global: false
          - service: botpress
  lang:
    image: botpress/server:latest
    expose:
      - port: 3100
        as: 3100
        to:
          - global: false
          - service: botpress
    command:
      - ./bp
      - lang
      - "--langDir"
      - /botpress/language
      - "--port"
      - "3100"

  redis:
    image: redis:5.0.5-alpine
    expose:
      - port: 6379
        as: 6379
        to:
          - service: botpress
    command:
      - redis-server
      - --requirepass
      - redisPassword

  postgres:
    image: postgres:13-alpine
    expose:
      - port: 5432
        as: 5432
        to:
          - global: false
          - service: botpress
    env:
      - POSTGRES_USER=bp_user
      - POSTGRES_PASSWORD=PG_PASSWORD
      - POSTGRES_DB=botpress_db
profiles:
  name: botpress
  duration: 30min
  mode: provider
  tier:
    - community
  compute:
    botpress:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          - size: 32Gi
    duckling:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          - size: 1Gi
    lang:
      resources:
        cpu:
          units: 8
        memory:
          size: 8Gi
        storage:
          - size: 32Gi
    postgres:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          - size: 20Gi
    redis:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          - size: 2Gi
  placement:
    westcost:
      attributes:
        region: us-central
      pricing:
        botpress:
          token: USDT
          amount: 5000000
        duckling:
          token: USDT
          amount: 5000000
        lang:
          token: USDT
          amount: 5000000
        postgres:
          token: USDT
          amount: 5000000
        redis:
          token: USDT
          amount: 5000000
deployment:
  botpress:
    westcost:
      profile: botpress
      count: 1
  duckling:
    westcost:
      profile: duckling
      count: 1
  lang:
    westcost:
      profile: lang
      count: 1
  postgres:
    westcost:
      profile: postgres
      count: 1
  redis:
    westcost:
      profile: redis
      count: 1
