version: "1.0"
services:
  gpu-test:
    image: docker.io/thumperai/torchbench:v0.0.10-cuda-12.0-dev
    expose:
      - port: 8888
        as: 80
        to:
          - global: true
    cmd:
      - '"jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"'
    env:
      - JUPYTER_TOKEN=passwd
profiles:
  name: hello-world
  duration: 2min
  tier:
    - community
  compute:
    gpu-test:
      resources:
        cpu:
          units: 1
        memory:
          size: 20Gi
        storage:
          - size: 100Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: a40
                - model: a10
                - model: rtx4090
                - model: rtx3090Ti
                - model: rtx4080
                - model: rtx3090
                - model: h100
                - model: a100
                - model: v100
                - model: rtx3060
                - model: p100
                - model: rtx4000
                - model: rtxa4000
                - model: rtx2070
                - model: gtx1080
                - model: 1080Ti
  placement:
    westcoast:
      attributes:
        region: us-central
      pricing:
        gpu-test:
          denom: USDT
          amount: 50000000
deployment:
  gpu-test:
    westcoast:
      profile: gpu-test
      count: 1
