version: "1.0"
services:
  gpu-test:
    image: ghcr.io/open-webui/open-webui:ollama
    expose:
      - port: 8888
        as: 80
        to:
          - global: true
    env:
      - TEST=test
profiles:
  name: hello-world
  mode: provider
  duration: 2min
  tier:
    - community
  compute:
    gpu-test:
      resources:
        cpu:
          units: 1
        memory:
          size: 20Gi
        storage:
          - size: 100Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx4090
                - model: rtx3090
                - model: h100
                - model: rtx6000
  placement:
    westcoast:
      attributes:
        region: us-central
      pricing:
        gpu-test:
          token: USDT
          amount: 50
deployment:
  gpu-test:
    westcoast:
      profile: gpu-test
      count: 1
